In [4]:
import torch.nn as nn
import torch




In [9]:
dropout = nn.Dropout(0.5)
x = torch.rand(2, 3, 3, 3)
print(x)

x = dropout(x)
print(x)

tensor([[[[0.2682, 0.3227, 0.8806],
          [0.6192, 0.5916, 0.0872],
          [0.2082, 0.1548, 0.7888]],

         [[0.7781, 0.1553, 0.0150],
          [0.7848, 0.1649, 0.7338],
          [0.1417, 0.1180, 0.7996]],

         [[0.0143, 0.6998, 0.5669],
          [0.5243, 0.9795, 0.7177],
          [0.4920, 0.6397, 0.3924]]],


        [[[0.1840, 0.1379, 0.0892],
          [0.9387, 0.7019, 0.4010],
          [0.1377, 0.7668, 0.8821]],

         [[0.0891, 0.4909, 0.3899],
          [0.1811, 0.5233, 0.9507],
          [0.0797, 0.7259, 0.8556]],

         [[0.0912, 0.3548, 0.8328],
          [0.5813, 0.6496, 0.5291],
          [0.0032, 0.3459, 0.5192]]]])
tensor([[[[0.5363, 0.0000, 1.7613],
          [0.0000, 1.1833, 0.1744],
          [0.4164, 0.3095, 1.5775]],

         [[1.5562, 0.3107, 0.0000],
          [1.5696, 0.3298, 0.0000],
          [0.0000, 0.0000, 1.5992]],

         [[0.0287, 0.0000, 0.0000],
          [0.0000, 1.9590, 0.0000],
          [0.0000, 1.2795, 0.0000]]],


     

In [13]:
x = torch.rand(1, 2, 3)
x.permute(2, 0, 1).shape

torch.Size([3, 1, 2])

In [33]:
x = torch.rand(2, 3, 4, 5)
x.flatten(0, 1, 2).shape

TypeError: flatten() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int start_dim, int end_dim, name out_dim)
      didn't match because some of the arguments have invalid types: (int, int, !int!)
 * (int start_dim, int end_dim)
 * (name start_dim, name end_dim, name out_dim)
      didn't match because some of the arguments have invalid types: (!int!, !int!, !int!)
 * (tuple of names dims, name out_dim)


In [36]:
torch.arange(10, dtype=torch.long).dtype

torch.int64

In [38]:
x = torch.arange(10, dtype=torch.long)
x.unsqueeze(0).expand(3, -1)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
x = torch.rand(10, 20, 3, dtype=torch.float64)
model = nn.Linear(3, 5)
y = model(x)
y.shape

RuntimeError: mat1 and mat2 must have the same dtype

In [56]:
x = torch.tensor([1, 2, 3], dtype=int)
em = nn.Embedding(10, 3)
print(x.dtype)
y = em(x)
y

torch.int64


tensor([[-0.5663,  0.3739, -0.6358],
        [ 0.5998,  0.5944,  0.2021],
        [ 0.2157,  0.4980, -1.1422]], grad_fn=<EmbeddingBackward0>)

tensor([[1, 2, 4, 5],
        [4, 3, 2, 9]])

In [61]:
x = torch.rand(10, 512, 256)
y = torch.rand(10, 512, 25)
(x+y).shape

RuntimeError: The size of tensor a (256) must match the size of tensor b (25) at non-singleton dimension 2

In [63]:
x = torch.rand(10, 512, 256)
x.new_zeros((1,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [71]:
x = torch.tensor([[1, 2, 3], [1, 2, 3]], dtype=torch.float32)
y = torch.softmax(x, dim=1)
print(y)


tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [89]:
from torch.utils.data import Dataset
from PIL import Image
from pathlib import Path
from typing import Callable, Optional, Union


class PPOCRDataset(Dataset):
    """_summary_
        PPOCR에서 사용하는 형식의 레이블 파일을 통해 데이터 셋을 로드하는 torch.Dataset
    Args:
        datasets (_type_): _description_
    """
    def __init__(self, data_dir:str, file_path:str, transform:Optional[Callable]=None):
        self.data_dir = Path(data_dir)
        self.samples = PPOCRDataset.load_samples(file_path) # [(img_path, label), ...]
        self.num_samples = len(self.samples)
        self.transform = transform
        
    @staticmethod
    def load_samples(path):
        with open(path, "r") as f:
            lines = [line.rstrip("\n").split("\t") for line in f.readlines()]
        return lines
    
    @staticmethod
    def load_image(path):
        return Image.open(path).convert("RGB")
        
    def __len__(self):
        return self.num_samples

    def __getitem__(self, index):
        img_path, label = self.samples[index]
        img = PPOCRDataset.load_image(self.data_dir/img_path)
        
        if self.transform is not None:
            img = self.transform(img)
        return img, label
    
dataset = PPOCRDataset("/home/datasets/sangmu_str_MH_v2/", "/home/datasets/sangmu_str_MH_v2/label.txt")

In [88]:
dataset[0]

(<PIL.Image.Image image mode=RGB size=2149x317>, 'IBK WM 센터 광주')